POST http://localhost:8080/accounts
Content-Type: application/json

{
  "id": "AC-1",
  "owner": "Michael"
}

###

GET http://localhost:8080/accounts/AC-1

###

GET http://localhost:8080/accounts/DOES-NOT-EXIST

###

POST http://localhost:8080/accounts/AC-1/deposit
Content-Type: application/json

{
  "amount": 100
}

###

GET http://localhost:8080/accounts/AC-1/balance

###

POST http://localhost:8080/accounts/AC-1/withdraw
Content-Type: application/json

{
  "amount": 9999
}

###

POST http://localhost:8080/accounts/AC-1/deposit
Content-Type: application/json

{
  "amount": -50
}

###