POST http://localhost:8080/accounts
Content-Type: application/json

{
  "id": "AC-DE-2026-01",
  "owner": "Michael Marques"
}

###
POST http://localhost:8080/accounts
Content-Type: application/json

{
  "id": ""
  "owner": "",
}

###

GET http://localhost:8080/accounts/AC-DE-2026-01

###

GET http://localhost:8080/accounts/DOES-NOT-EXIST

###

POST http://localhost:8080/accounts/AC-DE-2026-01/deposit
Content-Type: application/json

{
  "amount": 100
}

###

GET http://localhost:8080/accounts/AC-DE-2026-01/balance

###

POST http://localhost:8080/accounts/AC-DE-2026-01/withdraw
Content-Type: application/json

{
  "amount": 9999
}

###

POST http://localhost:8080/accounts/AC-DE-2026-01/deposit
Content-Type: application/json

{
  "amount": -50
}

###